run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters
    - bodyclose        # Checks whether HTTP response body is closed
    - contextcheck     # Check for context.Context passed to functions
    - dupl             # Detect duplicate code
    - durationcheck    # Check for two durations multiplied together
    - errname          # Check error names
    - errorlint        # Find code that can cause problems with error wrapping
    - exhaustive       # Check exhaustiveness of enum switch statements
    - goconst          # Find repeated strings that could be constants
    - gocritic         # Various checks
    - gofmt            # Check if code is formatted
    - goimports        # Check imports
    - gosec            # Security checks
    - misspell         # Find misspelled words
    - nakedret         # Find naked returns
    - nilerr           # Find code that returns nil even if error is not nil
    - nilnil           # Check for returning nil, nil
    - noctx            # Find HTTP requests without context.Context
    - prealloc         # Find slice declarations that could be preallocated
    - predeclared      # Find shadowed predeclared identifiers
    - revive           # Fast, configurable linter
    - rowserrcheck     # Check sql.Rows.Err is checked
    - sqlclosecheck    # Check sql.Rows and sql.Stmt are closed
    - stylecheck       # Stylecheck
    - tenv             # Detect using os.Setenv in tests
    - tparallel        # Detect misuse of t.Parallel
    - unconvert        # Remove unnecessary type conversions
    - unparam          # Find unused function parameters
    - wastedassign     # Find wasted assignments

linters-settings:
  dupl:
    threshold: 150
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  exhaustive:
    default-signifies-exhaustive: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint  # We don't require nolint comments to have explanations
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/yourorg/volt
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck for this)
      - G304  # File inclusion via variable (often false positive)
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy, minor optimization
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    for-loops: true
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  
  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - errcheck
    
    # Exclude some linters from running on examples
    - path: examples/
      linters:
        - errcheck
        - gosec
    
    # Allow unused parameters in interface implementations
    - linters:
        - unparam
      text: "always receives"
  
  max-issues-per-linter: 50
  max-same-issues: 10
